added yml file and changed MySQL corrections

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,27 +1,75 @@
-name: Playwright Tests
+name: Playwright Smoke Tests
+
 on:
   push:
-    branches: [ main, master ]
+    branches:
+      - main
+
   pull_request:
-    branches: [ main, master ]
+    branches:
+      - main
+
+  workflow_dispatch:
+
 jobs:
-  test:
-    timeout-minutes: 60
+  playwright:
     runs-on: ubuntu-latest
+
+    timeout-minutes: 60
+
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/setup-node@v4
-      with:
-        node-version: lts/*
-    - name: Install dependencies
-      run: npm ci
-    - name: Install Playwright Browsers
-      run: npx playwright install --with-deps
-    - name: Run Playwright tests
-      run: npx playwright test
-    - uses: actions/upload-artifact@v4
-      if: ${{ !cancelled() }}
-      with:
-        name: playwright-report
-        path: playwright-report/
-        retention-days: 30
+
+      # Download code
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+
+      # Setup Node
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 22
+          cache: npm
+
+
+      # Verify environment
+      - name: Display Environment
+        run: |
+          node -v
+          npm -v
+          pwd
+          ls -la
+
+
+      # Install npm packages
+      - name: Install Dependencies
+        run: npm ci
+
+
+      # Install Playwright browsers
+      - name: Install Playwright Browsers
+        run: npx playwright install --with-deps
+
+
+      # Execute API Tests
+      - name: Run API Tests
+        run: npm run API_Test
+        continue-on-error: false
+
+
+      # Check generated reports
+      - name: Verify Reports Folder
+        if: always()
+        run: |
+          echo "Checking Reports folder..."
+          ls -R Reports || echo "Reports folder not found"
+
+
+      # Upload Smart Report
+      - name: Upload Playwright Smart Report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: Playwright-Smart-Report
+          path: Reports/
+          retention-days: 30
